SET ( LIBB64_BUFFERSIZE "16777216" )

IF ( WIN32 )
    SET ( CORELIB_DEFINES "_UNICODE; UNICODE; WIN32_LEAN_AND_MEAN" )
ENDIF (  )

IF ( WIN32 )
    SET ( RESTFUL_PROJECT_DEFINES "_UNICODE; UNICODE; WIN32_LEAN_AND_MEAN" )
ENDIF (  )


