SET ( FOOTPAL_PRODUCT_COMPANY_NAME "CompanyName" )
SET ( FOOTPAL_PRODUCT_COPYRIGHT_HOLDER "CopyrightHolder" )
SET ( FOOTPAL_PRODUCT_COPYRIGHT_YEAR "2014" )
SET ( FOOTPAL_PRODUCT_COPYRIGHT "(C) ${FOOTPAL_PRODUCT_COPYRIGHT_YEAR} ${FOOTPAL_PRODUCT_COPYRIGHT_HOLDER}" )

SET ( FOOTPAL_RESTFUL_PROJECT_PRODUCT_INTERNAL_NAME "FootpalRESTful" )
SET ( FOOTPAL_RESTFUL_PROJECT_PRODUCT_NAME "Footpal RESTful Web Service" )
SET ( FOOTPAL_RESTFUL_PROJECT_PRODUCT_VERSION_MAJOR "0" )
SET ( FOOTPAL_RESTFUL_PROJECT_PRODUCT_VERSION_MINOR "1" )
SET ( FOOTPAL_RESTFUL_PROJECT_PRODUCT_VERSION_PATCH "0" )
SET ( FOOTPAL_RESTFUL_PROJECT_PRODUCT_DESCRIPTION "This is the RESTful web service for Footpal" )

IF ( EXISTS "${PROJECT_SOURCE_DIR}/../.git" )
    EXEC_PROGRAM ( ${GIT_EXECUTABLE}
        ARGS "--git-dir=\"${PROJECT_SOURCE_DIR}/.git\" --work-tree=\"${PROJECT_SOURCE_DIR}\" describe --always"
        OUTPUT_VARIABLE GIT_SHORT_REVISION_HASH )
    SET ( FOOTPAL_RESTFUL_PROJECT_PRODUCT_VERSION_REVISION ${GIT_SHORT_REVISION_HASH} )
ELSE (  )
    SET ( FOOTPAL_RESTFUL_PROJECT_PRODUCT_VERSION_REVISION "{non-git}" )
ENDIF (  )

SET ( FOOTPAL_RESTFUL_PROJECT_PRODUCT_VERSION "${FOOTPAL_RESTFUL_PROJECT_PRODUCT_VERSION_MAJOR}.${FOOTPAL_RESTFUL_PROJECT_PRODUCT_VERSION_MINOR}.${FOOTPAL_RESTFUL_PROJECT_PRODUCT_VERSION_PATCH}-${FOOTPAL_RESTFUL_PROJECT_PRODUCT_VERSION_REVISION}" )


